version: '3.9'

services:
  go-web-app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/go.mod
      - /app/go.sum
    command: sh -c "go build -o main && ./main"
